service:
  name: picksmatch-ssr
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./config/webpack.config.server.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: prod
  # apiGateway:
  #   minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  # environment:
  #   AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  app:
    handler: server/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}
